### ISSUE TITLE
random-page-plugin.js causes error

### ISSUE THREAD

**Issue by 8bitgentleman** [oschmid/roam-plugins#1]
As of today's latest Roam update your (excellent) random-page plugin has started to cause some errors.

**Comment by 8bitgentleman** [comment]
Whoop spoke to soon. Looks like Clear Sidebar plugin is also causing errors.
I’m no JS expert but it seems to have something to do with the loading on first run. I think they’re querying for something that hasn’t loaded yet? The plugins work just find when run on their own but throw an error when roam is first opened or reloaded.

**Comment by oschmid** [comment]
Turns out it affected all my plugins as they were each trying to select DOM nodes before the main Roam app had created them. I've added a delay to give Roam more time and that seems to have fixed things. I might go back and try to get the plugins to listen for DOMNodeInserted events but this seems good enough for now.

**Comment by oschmid** [comment]
Fixed in commit 0e67dda3296721c84a241f81f01efac5bf3e3173
